/**
 * Hard-coded list os cat data
 * @author Chris Loftus
 * @version 1
 */
package uk.ac.aber.dcs.cs31620.faa.model

import uk.ac.aber.dcs.cs31620.faa.R
import java.time.LocalDate

class CatList {
    val cats = listOf(
       Cat("Tibs", Gender.MALE, "Short hair",
           "Lorem ipsum dolor sit amet, ...",
           R.drawable.cat1,
           LocalDate.now()),
        Cat("Tibs", Gender.MALE, "Short hair",
            "Lorem ipsum dolor sit amet, ...",
            R.drawable.cat1,
            LocalDate.now()),
        Cat("Tibs", Gender.MALE, "Short hair",
            "Lorem ipsum dolor sit amet, ...",
            R.drawable.cat1,
            LocalDate.now()),
        Cat("Tibs", Gender.MALE, "Short hair",
            "Lorem ipsum dolor sit amet, ...",
            R.drawable.cat1,
            LocalDate.now()),
        Cat("Tibs", Gender.MALE, "Short hair",
            "Lorem ipsum dolor sit amet, ...",
            R.drawable.cat1,
            LocalDate.now()),
        Cat("Tibs", Gender.MALE, "Short hair",
            "Lorem ipsum dolor sit amet, ...",
            R.drawable.cat1,
            LocalDate.now()),
        Cat("Tibs", Gender.MALE, "Short hair",
            "Lorem ipsum dolor sit amet, ...",
            R.drawable.cat1,
            LocalDate.now()),
        Cat("Tibs", Gender.MALE, "Short hair",
            "Lorem ipsum dolor sit amet, ...",
            R.drawable.cat1,
            LocalDate.now()),
        Cat("Tibs", Gender.MALE, "Short hair",
            "Lorem ipsum dolor sit amet, ...",
            R.drawable.cat1,
            LocalDate.now()),
        Cat("Tibs", Gender.MALE, "Short hair",
            "Lorem ipsum dolor sit amet, ...",
            R.drawable.cat1,
            LocalDate.now()),
        Cat("Tibs", Gender.MALE, "Short hair",
            "Lorem ipsum dolor sit amet, ...",
            R.drawable.cat1,
            LocalDate.now()),
        Cat("Tibs", Gender.MALE, "Short hair",
            "Lorem ipsum dolor sit amet, ...",
            R.drawable.cat1,
            LocalDate.now()),
        Cat("Tibs", Gender.MALE, "Short hair",
            "Lorem ipsum dolor sit amet, ...",
            R.drawable.cat1,
            LocalDate.now()),
        Cat("Tibs", Gender.MALE, "Short hair",
            "Lorem ipsum dolor sit amet, ...",
            R.drawable.cat1,
            LocalDate.now()),
        Cat("Tibs", Gender.MALE, "Short hair",
            "Lorem ipsum dolor sit amet, ...",
            R.drawable.cat1,
            LocalDate.now()),
        Cat("Tibs", Gender.MALE, "Short hair",
            "Lorem ipsum dolor sit amet, ...",
            R.drawable.cat1,
            LocalDate.now()),
        Cat("Tibs", Gender.MALE, "Short hair",
            "Lorem ipsum dolor sit amet, ...",
            R.drawable.cat1,
            LocalDate.now()),
        Cat("Tibs", Gender.MALE, "Short hair",
            "Lorem ipsum dolor sit amet, ...",
            R.drawable.cat1,
            LocalDate.now()),
        Cat("Tibs", Gender.MALE, "Short hair",
            "Lorem ipsum dolor sit amet, ...",
            R.drawable.cat1,
            LocalDate.now()),
        Cat("Tibs", Gender.MALE, "Short hair",
            "Lorem ipsum dolor sit amet, ...",
            R.drawable.cat1,
            LocalDate.now())
    )
}